apiVersion: batch/v1
kind: Job
metadata:
  name: hello-client
spec:
  template:
    metadata:
      name: hello-client
    spec:
      containers:
      - name: hello-client
        image: busybox
        command: ["wget"]
        args: ["-O", "-", "hello-server:8081"]
      restartPolicy: OnFailure
