apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-server
    spec:
      containers:
      - name: hello-server
        image: functicons/hello-k8s
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-server
spec:
  ports:
    - port: 8081
      targetPort: 8080
  selector:
    app: hello-server
